language: java
sudo: false
jdk: oraclejdk8

before_install:
  - chmod ugo+x mvnw

install:
  - ./mvnw compile

cache:
  directories:
  - .autoconf
  - $HOME/.m2

jobs:
  include:
    - stage: test
      script:
        - ./mvnw verify
    - stage: deploy
      script:
        - ./mvnw package -Dmaven.test.skip=true
      after_success:
       - bash <(curl -s https://codecov.io/bash)
